skinparam backgroundColor #1E1E2E
skinparam defaultTextAlignment center
skinparam shadowing false
skinparam ArrowColor #A6E3A1
skinparam ActorBackgroundColor #313244
skinparam ActorBorderColor #A6E3A1
skinparam SequenceLifeLineBorderColor #89B4FA
skinparam DefaultTextColor #A6E3A1
